### ISSUE TITLE
Issue: the Lives counter won't go down and the timer will get stuck at 0:00 when the stage restarts

### ISSUE THREAD

**Issue by HexagonalX** [VectorSatyr/SonicGMS#1]
Hello, i'd like to point out that if sonic get's crushed/fall into a pit/etc. the lives count won't drain by 1 and the timer will freeze at 0:00

**Comment by VectorSatyr** [comment]
While the DevControl object is active in a level, the player cannot lose lives; this makes it easier to diagnose problems. By default, DevControl is active in all available levels in the template.

Also, DemoZone2 does not have a ZoneTimeLimit object, and so the timer will not count up in that level. This is meant to demonstrate the modularity of the object system in the template.

Please let me know if you are still experiences these issues even in spite of the above.
