### ISSUE TITLE
Sonic For GMS now supported by Game Maker Studio 2

### ISSUE THREAD

**Issue by Bluecoreg** [VectorSatyr/SonicGMS#10]
A new update to GMS2 finally fixed the 1.4 importer, and now the Sonic For GMS engine runs well using it. The only issue is object FileSelectMenu uses a temporary variable called layer, which is now the name of a built-in variable. Changing this name allows the game to run fine on both VM and YYC mode.

If you think it might be worthwhile to support GMS2 as well, I could send you a key to the software if you don't already own it.
(Also I apologize, issues isn't the right place for this)

**Comment by VectorSatyr** [comment]
Send it to me via e-mail.
