### ISSUE TITLE
Snapping and getting stuck on terrain

### ISSUE THREAD

**Issue by TheMCNerd2017** [VectorSatyr/SonicGMS#11]
I found this bug when testing out different terrain layouts. Basically, you either get stuck in a single place building up speed until you jump, or you snap to the terrain below. I uploaded a video to YouTube showing the bug in action: https://www.youtube.com/watch?v=_YQiwt1-3FE

I am not sure if this is intentional, or if it can be fixed normally. It only seems to happen when curve terrain is next to normal terrain. I am not sure if this happens if curve terrain is next to slopes, but I will test that out if needed.

**Comment by VectorSatyr** [comment]
@TheMCNerd2017 Thank you for sharing this issue with me. I am working on a fix for getting stuck on the terrain; however, I do not believe snapping to the terrain is a bug in this case. Could you demonstrate why this would be an issue?

**Comment by TheMCNerd2017** [comment]
@VectorSatyr I'm not sure what you meant by demonstrating how it would be an issue, but I uploaded another video showing the player snapping to terrain strangely: https://www.youtube.com/watch?v=QB7y3xgSWXU

Basically the player snaps to the top of curves (preventing them from falling normally), and snaps to shallow slopes next to curves (preventing them from launching into the air normally).

**Comment by VectorSatyr** [comment]
@TheMCNerd2017 This should be fixed as of the latest commit. Please let me know if there are still issues.

**Comment by TheMCNerd2017** [comment]
OK, I'll let you know if any other issues come up.
