### ISSUE TITLE
Player does not properly stay in the death state when spindashing into a spike underwater

### ISSUE THREAD

**Issue by TheMCNerd2017** [VectorSatyr/SonicGMS#12]
Not sure if this is because of how the spike is set up, but when the player spindashes into a spike underwater, they are put into the death state for about a frame before being placed back on the ground and are able to do normal actions until the room resets.

Video of the bug in action: https://www.youtube.com/watch?v=GOzaN1x_ItU

**Comment by VectorSatyr** [comment]
This has been fixed as of the latest commit.
