### ISSUE TITLE
How am I suppose to make the main character properly jump to another object's coordinates?

### ISSUE THREAD

**Issue by TheMCNerd2017** [VectorSatyr/SonicGMS#13]
Sorry if I'm not allowed to ask this here. I wasn't sure where I could ask questions on how to fix something.

I'm attempting to implement the classic debug mode from S3K into the engine (I prefer it over the current one, which is kind of limited). I've run into an issue though while implementing it: the player character does not seem to be jumping to the debug object's coordinates properly.

I'm putting the player into the already provided debug state (which I removed the movement code from) with this code:
`if (game_player_find(0) != noone) { 
        with (game_player_find(0)) {
            if instance_exists(character) {
                with (character) {
                    game_pc_perform(self, player_is_debug);
                }
            }
        }
        debug_active = 1;
    }`

and attempting to make the player jump to the debug object with this code:
`with (game_player_find(0)) {
        if instance_exists(character) {       
            character.x = other.x;
            character.y = other.y;
        }
    }`

Sorry that it looks sloppy. I'm not sure how to keep the formatting and line breaks. Also I uploaded a video of what happens in-game: https://youtu.be/G-hyQKXOW6w

Am I doing something wrong? Or am I suppose to be controlling the coordinates in another way?

**Comment by Bluecoreg** [comment]
You need to use `game_pc_position` to move the player or change the player's position.

**Comment by VectorSatyr** [comment]
Basically, what @Bluecoreg said.

`var player = game_player_find(0);
if (player != noone) {
    var character = player.character;
    if (character != noone) {
        game_pc_position(character, x, y);
   }
}`

Hope this helps.

**Comment by TheMCNerd2017** [comment]
@Bluecoreg @VectorSatyr OK, thanks for telling me.
