### ISSUE TITLE
Engine crashes when exiting the player_is_debug state while a newly-placed ring is attracted to you and an enemy is colliding with you

### ISSUE THREAD

**Issue by TheMCNerd2017** [VectorSatyr/SonicGMS#19]
Just discovered this when implementing some of the recent bug fixes into my own build of the engine. Basically, when you create a new WorldRing object in the stage, get it attracted to you, go into the player_is_debug state, and exit the player_is_debug state while the newly attracted WorldRing and an enemy is colliding with you, the game instantly crashes with an error message.

I was able to replicate this in both my [own build](https://www.youtube.com/watch?v=MvegIJoz4Z0) and the [latest GitHub version](https://www.youtube.com/watch?v=crHpTpx6Wv8) of the engine.

**Comment by VectorSatyr** [comment]
@TheMCNerd2017 Please re-test.

**Comment by TheMCNerd2017** [comment]
Ok, I'll go and retest for the bug and report back if it happens again or not.

**Comment by TheMCNerd2017** [comment]
I just re-tested it, and it looks like the issue is fixed.
