### ISSUE TITLE
Couple questions about how your shader engine works

### ISSUE THREAD

**Issue by Bluecoreg** [VectorSatyr/SonicGMS#3]
![GIF](https://user-images.githubusercontent.com/36262058/57103105-e87e7d80-6cf2-11e9-8455-4f5c1f9871e8.gif)

1) Is it possible to have multiple shaders being used at the same time? If not, not a big deal.
2) Does the shader engine only support four colors? I did this,
`normal_color = array_create(5);`
`first_array = array_create(5);`
`second_array = array_create(5);`
`third_array = array_create(5);`
`fourth_array = array_create(5);`
Using `array_create(5);` instead of `array_create(4);`
And set up the fifth color the same way I did the others, yet still only the first four colors animate.
3) Is there a way to disable shaders for specific parts? Like the HUD.

**Comment by VectorSatyr** [comment]
1. Depends on how they're used, but generally no.
2. Yes, only four colors are supported.
3. You have to capture the parts of the screen you want to apply the shader to yourself, and then draw it over them if you want to ignore stuff like the HUD.
