### ISSUE TITLE
Force Layer for loops entrance and exit

### ISSUE THREAD

**Issue by Bluecoreg** [VectorSatyr/SonicGMS#4]
I see there is LayerFlip object, but if the player jumps over the loop, they won't be able to go through the loop backwards. Is there a way to force the entrance and exits layers of loops?

**Comment by VectorSatyr** [comment]
As shown in the sample room DemoZone1, you need to place another somewhere in the space the player can travel around the loop. Your best bet is place one in front of the loop, and one behind the loop with the image_xscale inverted (the arrow should point the other direction.)

**Comment by Bluecoreg** [comment]
Thanks! Didn't realize setting the image_xscale did something!
