### ISSUE TITLE
Is it possible to disable player's actions, like player_is_falling, player_is_running, for a while?

### ISSUE THREAD

**Issue by Bluecoreg** [VectorSatyr/SonicGMS#5]
Trying to add zoom tubes in the form of pathing. Just want the player to follow a path, and then resume normal routines after the path is done.

**Comment by VectorSatyr** [comment]
The general idea is that you create a reaction script that initiates the path, sets `linked_object_id` to the instance id of the object that initiated it, and sets the player's state to `player_is_linked`. You then set the step event of the object to something along the lines of:

`if (game_is_running()) {
    with (PlayerCharacter) {
        if (linked_object_id == other) {
            // check for path end, then change state and release from object
        }
    }
}

**Comment by Bluecoreg** [comment]
It works. Cheers mate.
