### ISSUE TITLE
Quick rundown on how the loop points works?

### ISSUE THREAD

**Issue by Bluecoreg** [VectorSatyr/SonicGMS#8]
game_audio_fmod_add_sound(path + "Studiopolis1Music.ogg", **4663458**);

Looking through the .ogg file, I have no idea where that numbers comes from.

**Comment by VectorSatyr** [comment]
The loop point is measured in samples. I just added the music file to Audacity and tried to eyeball where it should loop. Not really a better way to do it, AFAIK.

**Comment by Bluecoreg** [comment]
Okay, that makes sense, thank you. I'll write up a method for finding the loop point for anyone else who may wonder.

Find the .ogg file of the song you want to use.
Open it up in Audacity.
Find where you want the song to start the loop at.
In the bottom of Audacity, look for the words that say "Audio Position."

For my case, I'm using the music for Spring Yard Zone. So the intro starts at 0 seconds. The intro ends at 2.299 seconds, so we want the song to start at 2.299 seconds every time the song played after it has already been played fully once for it to loop properly.

Anyways, now that you have your time. To the left of "Audio Position" in Audacity is the "Project Rate."
Take that number, and multiply it by the seconds you got earlier.

In my case, I got the number 101385.9(decimals are allowed) which is the loop point!

After that, make sure to include the .ogg file in the Included Files, Audio folder in game maker.
In the Game Start event of the FMODAudioSystem object, add the .ogg file there as well just like "Studiopolis1Music" has been.

Lastly, in the room you want to use the music, in the creation code for the GameZone object, set music equal to the name of the file, wrapped by quotes, except don't include the ".ogg" part.
