### ISSUE TITLE
Small question about roll_slope_friction_up inside of the script game_pc_refresh_physics

### ISSUE THREAD

**Issue by Bluecoreg** [VectorSatyr/SonicGMS#9]
`roll_slope_friction_up = 0.071825;`

In the Sonic Retro Physics guide, they have a constant called slprollup set to 0.078125
http://info.sonicretro.org/SPG:Solid_Tiles

Did you mean to use their value?

**Comment by VectorSatyr** [comment]
I did not. Nevertheless, the value in the build is likely a typo. I have pushed a fix.
